language: scala
scala:
  - 2.12.12
  - 2.13.3
before_install:
  - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then bash
    -x scripts/decrypt_keys.sh; fi
  - export PATH=${PATH}:./vendor/bundle
install:
  - rvm use 2.6.0 --install --fuzzy
  - gem update --system
  - gem install sass
  - gem install jekyll -v 4.0.0
  - gem install jemoji -v 0.11.1
  - gem install jekyll-sitemap -v 1.4.0
script:
- sbt ++$TRAVIS_SCALA_VERSION clean coverage test coverageReport
after_success:
- bash <(curl -s https://codecov.io/bash)
- if [ "$TRAVIS_BRANCH == "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then sbt ++$TRAVIS_SCALA_VERSION clean coverageOff compile publish; fi
- if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then bash scripts/publish_microsite.sh; fi
env:
  global:
  - secure: XLAW90dZEXLQIquOiGTKeBAy6VfbQqd5O5ZVxpmunNoABvU8SJOyvwU1XvVAcAXMlGLj/JglZd2OhvM0BSSsceSO1c6WkdGEBLQT970bfbtIvCte4ZopGSaFL1YcQ3QjF0KG9ZnmoL0Ittuss/+jKrsvS/xd6zTZ0Xav5Ah/7fXjM1F4KxTau5KAOW3PU/u2NZdonpc1Hp0C/wTtXiH4yy7HdY1tDMlV4PFPyY8ORiscE/NmwqqQNcdSZcvA9hos9Lk+cC2nMW1NPlbpScNJjBz/LY/XWwz5SX142pez/pUSvXIdf007NfghSwwRCtcEdnWb/VQjmGMpupmu8ttGgpt9HsIfx7Xvasj6Nh8wWhUo5w3heJzDHsD7v/1ToHc6Su7ILVaXYBq0SxMt1+C5z9PUe8eq8/+Y5cEejj/uKYxm52Q4rLD3i+ULPLy1WZ+4Yld+lSKlLbzMXxxWD+/GU4t+MlOWmTjIZTxUuU6LYNvIxd3hsnlf5/7pf/anOfTJ96z/IOAKrXZV9PmIKAi027bUZz3CMvWo5p0DOmJYEa2SwJuKhfea0ZszNJSyTD479SwUGewOTDF4JW6hAB8wKNC11Ptnc1HyRqALF3TIY+fUJyLfQh5Djp6GOeP8J5JjAhvP8Zbz0Fi2ezSKtoo2MaVVj/sj4c9Hv50ArEwJD90=
  - secure: O3bgudb5+OAoe7jBZD3aqvQKJWBu3mIChCn33eQGN/g5aWYYr9i5f/f2BgU0enpWkfr0Pu3U5nQMQeXE17htxl898I+Hjc76lm0YduuUPY9pXrdynK2Ab+PfkyvjoEEAlHuy7GwjjV080SnlwQA5lXU3x6Nz67eawiNVOAfKIZdIAoQiYNBCsEaRKhtkTQ4nseMRoWIhkBSjFEkMEdr+ijYyei/jlsbDb631blTReAbjz/Khy4MKRE+FZiM0hi9RDUy01SWvVBrp7lunXwXXEUrT0HbyARqBxkqo+xcjGkUV/fpmBI8r0jLTHFhRyXAGJDfK1WtEfr+a7U4JJqVhGAtgd1sLy0s6ou5bCioJH6FGfiqWMlqywzwGLlz7Xl1smwKVTpDGUIahQODLA+Y0To4iwLcJhWxyhzFjfG4LgQh7EMgYfIWHJPLJlp/f3nn+gjGvGGWhAmA1HJR/eYqG76BRlVqK5x6sawXx0Ecitzuvvyx974B3r8PKqTUmDy5OlGw0FRS6kin0fNt5pHlU1Scw9ZTwBJzHbuOE2PST5AQnE0jhOfjTDO2CbdLu2FSTUf+BXtCY80Sd1xxB+My1G4EMNNlLWldS8UaTWqiF3cvre0QcIExqDSsew5TbnKCEYqS7JFLvXFsdv7DCxkadwUEGukxsa3Xfp5L/lS5Ci7M=
